// Converts data-src/kerala-districts.geojson into SVG paths: js/data/map.js
//   node scripts/build-map.mjs
import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "..");
const geo = JSON.parse(fs.readFileSync(path.join(ROOT, "data-src/kerala-districts.geojson"), "utf8"));

const rings = (g) => (g.type === "Polygon" ? g.coordinates : g.coordinates.flat());
let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
for (const f of geo.features)
  for (const r of rings(f.geometry))
    for (const [x, y] of r) {
      minX = Math.min(minX, x); maxX = Math.max(maxX, x);
      minY = Math.min(minY, y); maxY = Math.max(maxY, y);
    }

// Equirectangular projection corrected for Kerala's latitude.
const k = Math.cos((((minY + maxY) / 2) * Math.PI) / 180);
const PAD = 10, W = 400;
const scale = (W - PAD * 2) / ((maxX - minX) * k);
const H = Math.round((maxY - minY) * scale + PAD * 2);
const project = ([lon, lat]) => [PAD + (lon - minX) * k * scale, PAD + (maxY - lat) * scale];
const r1 = (n) => Math.round(n * 10) / 10;

const districts = {};
for (const f of geo.features) {
  const id = f.properties.DISTRICT.toLowerCase();
  let d = "", A = 0, CX = 0, CY = 0;
  for (const ring of rings(f.geometry)) {
    const pts = ring.map(project);
    d += "M" + pts.map(([x, y]) => `${r1(x)},${r1(y)}`).join("L") + "Z";
    for (let i = 0; i < pts.length - 1; i++) {
      const [x0, y0] = pts[i], [x1, y1] = pts[i + 1];
      const c = x0 * y1 - x1 * y0;
      A += c; CX += (x0 + x1) * c; CY += (y0 + y1) * c;
    }
  }
  districts[id] = { d, cx: r1(CX / (3 * A)), cy: r1(CY / (3 * A)) };
}

const out = {
  viewBox: `0 0 ${W} ${H}`,
  // Lets the site place lat/lon pins on the map.
  proj: { minX, maxY, k, scale, pad: PAD },
  districts,
};
fs.writeFileSync(
  path.join(ROOT, "js/data/map.js"),
  "/* Generated by scripts/build-map.mjs from DataMeet-derived boundaries (CC BY 4.0). */\nwindow.KERALA_MAP = " + JSON.stringify(out) + ";\n"
);
console.log("viewBox", out.viewBox, Object.keys(districts).length, "districts");
